name: Azure Static Web Apps CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_PATH=$HOME/.bun/bin" >> $GITHUB_ENV
          echo "PATH=$HOME/.bun/bin:\$PATH" >> $GITHUB_ENV

      # Use Bun to install dependencies and build
      - name: Install dependencies and build
        run: |
          bun install
          bun run build
        env:
          PATH: ${{ env.BUN_PATH }}:${{ env.PATH }}

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t my-app:latest .

      # Push Docker image to Azure Container Registry
      - name: Push Docker Image to Azure
        run: |
          echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login myregistry.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
          docker tag my-app:latest myregistry.azurecr.io/my-app:latest
          docker push myregistry.azurecr.io/my-app:latest

      - name: Build And Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ISLAND_04383B800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_ISLAND_04383B800 }}
          action: "close"
